/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Wolfram9 (https://sketchfab.com/Wolfram9)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/butterfly-diorama-260e957761db4bee8f7cd34e718a4704
Title: Butterfly diorama
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/scene.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="ButerflyDioramafbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" position={[11.459, 76.499, 0.006]} rotation={[0.53, 0, 0]} scale={3.61}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                  </group>
                </group>
                <group name="Grass" position={[-34.245, 20.398, 136.652]} rotation={[-0.111, -1.165, -0.142]} scale={[2.049, 5.208, 2.049]}>
                  <mesh name="Grass_Earth_0" geometry={nodes.Grass_Earth_0.geometry} material={materials.Earth} />
                </group>
                <group name="Jar" position={[1.434, 52.919, 0]} rotation={[-1.526, -0.039, 0]} scale={31.289}>
                  <mesh name="Jar_Glass_0" geometry={nodes.Jar_Glass_0.geometry} material={materials.Glass} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
